aws_region          = "ap-southeast-2"
environment         = "production"
cluster_name        = "eks-prod-cluster"
cluster_version     = "1.36"
ecr_repository_name = "my-webapp"
availability_zones  = ["ap-southeast-2a", "ap-southeast-2b"]
node_instance_types = ["c7i-flex.large"]
desired_node_count  = 2
min_node_count      = 1
max_node_count      = 4
